routes/web.php
<?php

use App\Http\Controllers\EmployeeController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect()->route('login');
});

Auth::routes([
    'login'    => true,
    'logout'   => true,
    'register' => false,
    'reset'    => false,   // for resetting passwords
    'confirm'  => false,  // for additional password confirmations
    'verify'   => false,  // for email verification
]);

Route::get('/home', [HomeController::class, 'index'])->name('home');

Route::controller(EmployeeController::class)
    ->name('employee.')
    ->prefix('employee')
    ->middleware('auth')
    ->group(function(){

        Route::get('/index','index')->name('index');
        Route::get('/create','create')->name('create');
        Route::post('/store','store')->name('store');
        Route::get('/{id}/edit','edit')->name('edit');
        Route::post('/update/{id}','update')->name('update');
        Route::post('/destroy/{id}','destroy')->name('destroy');
    });

app/Models/Employee.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Auth;

class Employee extends Model
{
    use HasFactory;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'user_id',
        'avatar',
        'nip',
        'full_name',
        'phone',
        'job',
        'sex',
        'is_active',
    ];

    public function user()
    {
        return $this->belongsTo(User::class, 'user_id');
    }

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'is_active' => 'boolean',
    ];

    /**
     * Get the Avatar Url
     *
     * @return string
     */
    public function getAvatarUrlAttribute()
    {
        return asset('back/uploads/employees/' . $this->avatar);
    }

    /**
     * The "booting" method of the model.
     *
     * @return void
     */
    protected static function boot()
    {
        parent::boot();

        static::creating(function ($employee) {
            $employee->user_id = (Auth::check()) ? Auth::id() : 1;
        });
    }
}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
        'is_admin',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
        'is_admin' => 'boolean',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/EmployeeController.php
<?php

namespace App\Http\Controllers;

use App\Models\Employee;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\File;
use App\Http\Requests\StoreEmployeeRequest;
use App\Http\Requests\UpdateEmployeeRequest;

class EmployeeController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $employees = Employee::latest()->simplePaginate(5);

        return view('pages.employee.index', [
            'employees' => $employees
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('pages.employee.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreEmployeeRequest $request)
    {
        $data = Employee::create($request->validated());

        if ($request->safe(['avatar'])) {
            $avatar = $request->file('avatar');

            $fileName = $avatar->getClientOriginalName();
            $filePath = 'back/uploads/employees/';

            $avatar->move($filePath, $fileName);
            $data->avatar = $fileName;
            $data->save();
        }

        return redirect()
            ->route('employee.index')
            ->with('success', 'Data berhasil disimpan');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Employee  $employee
     * @return \Illuminate\Http\Response
     */
    public function show(Employee $employee)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Employee  $employee
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $employee = Employee::find($id);

        return view('pages.employee.edit', [
            'data' => $employee
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Employee  $employee
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateEmployeeRequest $request, $id)
    {
        $data = Employee::find($id);
        $data->update($request->validated());

        if ($request->safe(['avatar'])) {
            $avatar = $request->file('avatar');

            $fileName = $avatar->getClientOriginalName();
            $filePath = 'back/uploads/employees/';

            $upload = $avatar->move($filePath, $fileName);

            if ($upload) {
                $oldAvatar = $data->avatar;
                File::delete('back/uploads/employees/' . $oldAvatar);

                $data->avatar = $fileName;
                $data->save();
            }
        }

        return redirect()
            ->route('employee.index')
            ->with('success', 'Data berhasil diperbarui');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Employee  $employee
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $data = Employee::find($id);
        if ($data->avatar) {
            File::delete('back/uploads/employees/' . $data->avatar);
        }
        $data->delete();

        return redirect()
            ->route('employee.index')
            ->with('success', 'Data berhasil dihapus');
    }
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('home');
    }
}

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="alert alert-success" role="alert">
                    <h4 class="alert-heading">Hello, {{ Auth::user()->name }}</h4>
                    <p>{{ __("You're logged in") }}</p>
                    <hr>
                    <p class="mb-0">{{ __('Welcome back, whats up today?') }}</p>
                </div>
                <hr>
                <div id="carouselExampleIndicators" class="carousel slide border" data-bs-ride="carousel">
                    <div class="carousel-indicators">
                        <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="0"
                            class="active" aria-current="true" aria-label="Slide 1"></button>
                        <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="1"
                            aria-label="Slide 2"></button>
                        <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="2"
                            aria-label="Slide 3"></button>
                    </div>
                    <div class="carousel-inner">
                        <div class="carousel-item active">
                            <img src="{{ asset('Pictures/imran-suleiman-h06rFhtllmY-unsplash.jpeg') }}"
                                class="d-block w-100" alt="...">
                        </div>
                        <div class="carousel-item">
                            <img src="{{ asset('Pictures/spenser-sembrat-J23AXE8tPDo-unsplash.jpeg') }}"
                                class="d-block w-100" alt="...">
                        </div>
                        <div class="carousel-item">
                            <img src="{{ asset('Pictures/windows-lhDjusLtpP4-unsplash.jpeg') }}" class="d-block w-100"
                                alt="...">
                        </div>
                    </div>
                    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators"
                        data-bs-slide="prev">
                        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                        <span class="visually-hidden">Previous</span>
                    </button>
                    <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators"
                        data-bs-slide="next">
                        <span class="carousel-control-next-icon" aria-hidden="true"></span>
                        <span class="visually-hidden">Next</span>
                    </button>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/pages/employee/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title mb-4">
                            <span class="font-weight-bold">Buat Pegawai</span>
                            <span class="font-weight-bold">
                                <a href="{{ route('employee.index') }}" class="btn btn-sm btn-secondary">KEMBALI</a>
                            </span>
                        </h5>
                        <form action="{{ route('employee.store') }}" method="post" enctype="multipart/form-data">
                            @csrf
                            <div class="row mb-3">
                                <div class="col-lg-2">
                                    <label class="col-form-label">
                                        Foto
                                    </label>
                                </div>
                                <div class="col-lg-auto">
                                    <img src="https://via.placeholder.com/150" class="rounded mx-auto d-block border border-dark" width="150"
                                        height="150" alt="...">
                                </div>
                                <div class="col-lg">
                                    <input type="file" name="avatar" class="form-control">
                                    @error('avatar')
                                        <span class="text-danger">{{ $message }}</span>
                                    @enderror
                                </div>
                            </div>
                            <div class="row mb-3">
                                <div class="col-lg-2">
                                    <label class="col-form-label">
                                        NIP <span class="text-danger">*</span>
                                    </label>
                                </div>
                                <div class="col-lg-10">
                                    <input type="text" name="nip" class="form-control">
                                    @error('nip')
                                        <span class="text-danger">{{ $message }}</span>
                                    @enderror
                                </div>
                            </div>
                            <div class="row mb-3">
                                <div class="col-lg-2">
                                    <label class="col-form-label">
                                        Nama Lengkap <span class="text-danger">*</span>
                                    </label>
                                </div>
                                <div class="col-lg-10">
                                    <input type="text" name="full_name" class="form-control">
                                    @error('full_name')
                                        <span class="text-danger">{{ $message }}</span>
                                    @enderror
                                </div>
                            </div>
                            <div class="row mb-3">
                                <div class="col-lg-2">
                                    <label class="col-form-label">
                                        Jabatan <span class="text-danger">*</span>
                                    </label>
                                </div>
                                <div class="col-lg-10">
                                    <input type="text" name="job" class="form-control">
                                    @error('job')
                                        <span class="text-danger">{{ $message }}</span>
                                    @enderror
                                </div>
                            </div>
                            <div class="row mb-3">
                                <div class="col-lg-2">
                                    <label class="col-form-label">
                                        Nomor Telepon <span class="text-danger">*</span>
                                    </label>
                                </div>
                                <div class="col-lg-10">
                                    <input type="text" name="phone" class="form-control">
                                    @error('phone')
                                        <span class="text-danger">{{ $message }}</span>
                                    @enderror
                                </div>
                            </div>
                            <div class="row mb-3">
                                <div class="col-lg-2">
                                    <label class="col-form-label">
                                        Jenis Kelamin <span class="text-danger">*</span>
                                    </label>
                                </div>
                                <div class="col-lg-10">
                                    <div class="d-block">
                                        <div class="form-check form-check-inline">
                                            <input class="form-check-input" type="radio" name="sex" id="male" value="male">
                                            <label class="form-check-label" for="male">Male</label>
                                        </div>
                                        <div class="form-check form-check-inline">
                                            <input class="form-check-input" type="radio" name="sex" id="female" value="female">
                                            <label class="form-check-label" for="female">Female</label>
                                        </div>
                                    </div>
                                    @error('sex')
                                        <span class="text-danger">{{ $message }}</span>
                                    @enderror
                                </div>
                            </div>
                            <div class="d-grid gap-2 col-6 mx-auto">
                                <button type="submit" class="btn btn-success btn-block">Simpan</button>
                            </div>
                        </form>
                    </div>
                </div>

            </div>
        </div>
    </div>
@endsection

resources/views/pages/employee/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title mb-4">
                            <span class="font-weight-bold">Edit Pegawai</span>
                            <span class="font-weight-bold">
                                <a href="{{ route('employee.index') }}" class="btn btn-sm btn-secondary">KEMBALI</a>
                            </span>
                        </h5>
                        <form action="{{ route('employee.update',['id' => $data->id]) }}" method="post" enctype="multipart/form-data">
                            @csrf
                            <div class="row mb-3">
                                <div class="col-lg-2">
                                    <label class="col-form-label">
                                        Foto
                                    </label>
                                </div>
                                <div class="col-lg-auto">
                                    @isset($data->avatar)
                                    <img src="{{ $data->avatar_url }}" class="rounded mx-auto d-block border border-dark" width="150"
                                    height="150" alt="...">
                                    @endisset
                                    @empty($data->avatar)
                                    <img src="https://via.placeholder.com/150" class="img-thumbnail" width="150"
                                    height="150" alt="...">
                                    @endempty
                                </div>
                                <div class="col-lg">
                                    <input type="file" name="avatar" class="form-control">
                                    @error('avatar')
                                        <span class="text-danger">{{ $message }}</span>
                                    @enderror
                                </div>
                            </div>
                            <div class="row mb-3">
                                <div class="col-lg-2">
                                    <label class="col-form-label">
                                        NIP <span class="text-danger">*</span>
                                    </label>
                                </div>
                                <div class="col-lg-10">
                                    <input type="text" name="nip" class="form-control" value="{{ old('nip', $data->nip) }}">
                                    @error('nip')
                                        <span class="text-danger">{{ $message }}</span>
                                    @enderror
                                </div>
                            </div>
                            <div class="row mb-3">
                                <div class="col-lg-2">
                                    <label class="col-form-label">
                                        Nama Lengkap <span class="text-danger">*</span>
                                    </label>
                                </div>
                                <div class="col-lg-10">
                                    <input type="text" name="full_name" class="form-control" value="{{ old('full_name', $data->full_name) }}">
                                    @error('full_name')
                                        <span class="text-danger">{{ $message }}</span>
                                    @enderror
                                </div>
                            </div>
                            <div class="row mb-3">
                                <div class="col-lg-2">
                                    <label class="col-form-label">
                                        Jabatan <span class="text-danger">*</span>
                                    </label>
                                </div>
                                <div class="col-lg-10">
                                    <input type="text" name="job" class="form-control" value="{{ old('job', $data->job) }}">
                                    @error('job')
                                        <span class="text-danger">{{ $message }}</span>
                                    @enderror
                                </div>
                            </div>
                            <div class="row mb-3">
                                <div class="col-lg-2">
                                    <label class="col-form-label">
                                        Nomor Telepon <span class="text-danger">*</span>
                                    </label>
                                </div>
                                <div class="col-lg-10">
                                    <input type="text" name="phone" class="form-control" value="{{ old('phone', $data->phone) }}">
                                    @error('phone')
                                        <span class="text-danger">{{ $message }}</span>
                                    @enderror
                                </div>
                            </div>
                            <div class="row mb-3">
                                <div class="col-lg-2">
                                    <label class="col-form-label">
                                        Jenis Kelamin <span class="text-danger">*</span>
                                    </label>
                                </div>
                                <div class="col-lg-10">
                                    <div class="form-check form-check-inline">
                                        <input class="form-check-input" type="radio" name="sex" id="male" @checked($data->sex == 'male') value="male">
                                        <label class="form-check-label" for="male">Male</label>
                                    </div>
                                    <div class="form-check form-check-inline">
                                        <input class="form-check-input" type="radio" name="sex" id="female" @checked($data->sex == 'female') value="female">
                                        <label class="form-check-label" for="female">Female</label>
                                    </div>
                                    @error('sex')
                                        <span class="text-danger">{{ $message }}</span>
                                    @enderror
                                </div>
                            </div>
                            <div class="d-grid gap-2 col-6 mx-auto">
                                <button type="submit" class="btn btn-success btn-block">Perbarui</button>
                            </div>
                        </form>
                    </div>
                </div>

            </div>
        </div>
    </div>
@endsection

resources/views/pages/employee/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">
                            <span class="font-weight-bold">Daftar Pegawai</span>
                            <span class="font-weight-bold">
                                <a href="{{ route('employee.create') }}" class="btn btn-sm btn-success">BUAT BARU</a>
                            </span>
                        </h5>
                        <table class="table table-hover table-striped">
                            <thead>
                                <tr>
                                    <th>Foto</th>
                                    <th>NIP</th>
                                    <th>Nama</th>
                                    <th>Jabatan</th>
                                    <th>Jenis Kelamin</th>
                                    <th width="15%" class="text-center">Aksi</th>
                                </tr>
                            </thead>
                            <tbody>
                                @forelse ($employees as $item)
                                    <tr>
                                        <td>
                                            @isset($item->avatar)
                                                <img src="{{ $item->avatar_url }}" class="rounded d-block border border-dark"
                                                    width="50" height="50" alt="...">
                                            @endisset
                                        </td>
                                        <td>{{ $item->nip }}</td>
                                        <td>{{ $item->full_name }}</td>
                                        <td>{{ $item->job }}</td>
                                        <td>{{ $item->sex }}</td>
                                        <td class="text-center">
                                            <a href="{{ route('employee.edit', ['id' => $item->id]) }}"
                                                class="btn btn-sm btn-dark">UBAH</a>
                                            @if (auth()->user()->is_admin == true)
                                                |
                                                <a href="{{ route('employee.destroy', ['id' => $item->id]) }}"
                                                    class="btn btn-sm btn-danger"
                                                    onclick="event.preventDefault();
                                                                document.getElementById('destroy-form').submit();">HAPUS</a>

                                                <form id="destroy-form"
                                                    action="{{ route('employee.destroy', ['id' => $item->id]) }}"
                                                    method="POST" class="d-none">
                                                    @csrf
                                                </form>
                                            @endif
                                        </td>
                                    </tr>
                                @empty
                                    <tr>
                                        <td colspan="6" class="text-center"><span class="badge bg-warning">DATA
                                                KOSONG</span></td>
                                    </tr>
                                @endforelse
                            </tbody>
                        </table>
                        {{ $employees->links() }}
                    </div>
                </div>

            </div>
        </div>
    </div>
@endsection